// Biblioteca base de exercícios (source = 'system'). [nome, músculo principal, secundários, equipamento, tipo, instruções]
export type SeedExercise = [
  name: string,
  primary: string,
  secondary: string[],
  equipment: string,
  tracking: 'weight_reps' | 'bodyweight_reps' | 'duration',
  instructions: string,
];

export const EXERCISES: SeedExercise[] = [
  // Peito
  ['Supino reto com barra', 'chest', ['triceps', 'shoulders'], 'Barra', 'weight_reps', 'Deitado no banco, pega na barra um pouco mais larga que os ombros. Desce até ao peito com controlo e empurra sem levantar as costas do banco.'],
  ['Supino inclinado com halteres', 'chest', ['shoulders', 'triceps'], 'Halteres', 'weight_reps', 'Banco a 30–45°. Desce os halteres até ao nível do peito e empurra a convergir ligeiramente no topo.'],
  ['Supino declinado com barra', 'chest', ['triceps'], 'Barra', 'weight_reps', 'Banco declinado, pés bem presos. Desce a barra à parte baixa do peito e empurra.'],
  ['Crucifixo com halteres', 'chest', ['shoulders'], 'Halteres', 'weight_reps', 'Braços ligeiramente fletidos, abre em arco até sentir alongar o peito e fecha contraindo o peitoral.'],
  ['Peck deck (máquina)', 'chest', ['shoulders'], 'Máquina', 'weight_reps', 'Costas encostadas, cotovelos à altura dos ombros. Junta os braços à frente e volta devagar.'],
  ['Cruzamento de cabos', 'chest', ['shoulders'], 'Cabos', 'weight_reps', 'Passo à frente, tronco ligeiramente inclinado. Junta as mãos à frente do peito num arco.'],
  ['Flexões', 'chest', ['triceps', 'shoulders', 'abs'], 'Peso corporal', 'bodyweight_reps', 'Corpo em linha reta, mãos ligeiramente mais largas que os ombros. Desce o peito ao chão e empurra.'],
  ['Fundos nas paralelas', 'chest', ['triceps', 'shoulders'], 'Paralelas', 'bodyweight_reps', 'Tronco ligeiramente inclinado para a frente, desce até ~90° no cotovelo e empurra.'],
  // Costas
  ['Barra fixa (pronada)', 'lats', ['biceps', 'upper_back'], 'Barra fixa', 'bodyweight_reps', 'Pega pronada mais larga que os ombros. Puxa o peito à barra levando os cotovelos para baixo.'],
  ['Puxada na polia alta', 'lats', ['biceps', 'upper_back'], 'Polia', 'weight_reps', 'Peito para fora, puxa a barra até à parte alta do peito sem balançar o tronco.'],
  ['Remada curvada com barra', 'upper_back', ['lats', 'biceps', 'lower_back'], 'Barra', 'weight_reps', 'Tronco a ~45°, costas retas. Puxa a barra ao umbigo e desce controlado.'],
  ['Remada com haltere a uma mão', 'lats', ['upper_back', 'biceps'], 'Halteres', 'weight_reps', 'Apoio no banco. Puxa o haltere ao quadril mantendo o tronco estável.'],
  ['Remada sentado no cabo', 'upper_back', ['lats', 'biceps'], 'Cabos', 'weight_reps', 'Peito aberto, puxa o pegador ao abdómen juntando as omoplatas.'],
  ['Remada em T', 'upper_back', ['lats', 'biceps'], 'Barra', 'weight_reps', 'Tronco inclinado, puxa a carga ao peito com cotovelos junto ao corpo.'],
  ['Pullover com haltere', 'lats', ['chest'], 'Halteres', 'weight_reps', 'Braços quase estendidos, leva o haltere atrás da cabeça e volta pelo mesmo arco.'],
  ['Levantamento terra', 'lower_back', ['glutes', 'hamstrings', 'traps', 'quads'], 'Barra', 'weight_reps', 'Barra junto às pernas, costas neutras. Empurra o chão e estende anca e joelhos em conjunto.'],
  ['Encolhimento de ombros com halteres', 'traps', ['forearms'], 'Halteres', 'weight_reps', 'Sobe os ombros em direção às orelhas, sem rodar, e desce devagar.'],
  ['Hiperextensões', 'lower_back', ['glutes', 'hamstrings'], 'Banco de hiperextensões', 'bodyweight_reps', 'Desce o tronco com costas neutras e sobe até alinhar com as pernas.'],
  // Ombros
  ['Press militar com barra', 'shoulders', ['triceps', 'traps'], 'Barra', 'weight_reps', 'Em pé, barra à altura das clavículas. Empurra acima da cabeça com abdómen contraído.'],
  ['Press de ombros com halteres', 'shoulders', ['triceps'], 'Halteres', 'weight_reps', 'Sentado, halteres à altura das orelhas. Empurra acima da cabeça sem arquear as costas.'],
  ['Elevações laterais', 'shoulders', [], 'Halteres', 'weight_reps', 'Cotovelos ligeiramente fletidos, sobe os braços até à altura dos ombros.'],
  ['Elevações frontais', 'shoulders', ['chest'], 'Halteres', 'weight_reps', 'Sobe o haltere à frente até à altura dos ombros, sem balançar.'],
  ['Pássaro (elevações posteriores)', 'shoulders', ['upper_back'], 'Halteres', 'weight_reps', 'Tronco inclinado, abre os braços para os lados juntando as omoplatas.'],
  ['Face pull', 'shoulders', ['upper_back', 'traps'], 'Cabos', 'weight_reps', 'Corda à altura da cara, puxa em direção à testa abrindo os cotovelos.'],
  ['Remada alta com barra', 'shoulders', ['traps', 'biceps'], 'Barra', 'weight_reps', 'Barra junto ao corpo, sobe com cotovelos acima das mãos até ao peito.'],
  // Bíceps
  ['Curl com barra', 'biceps', ['forearms'], 'Barra', 'weight_reps', 'Cotovelos junto ao corpo, sobe a barra sem balançar e desce controlado.'],
  ['Curl com halteres alternado', 'biceps', ['forearms'], 'Halteres', 'weight_reps', 'Roda o pulso ao subir (supinação) e desce devagar, alternando os braços.'],
  ['Curl martelo', 'biceps', ['forearms'], 'Halteres', 'weight_reps', 'Pega neutra (palmas viradas uma para a outra), cotovelos fixos.'],
  ['Curl no banco Scott', 'biceps', [], 'Barra', 'weight_reps', 'Braços apoiados no banco, desce até quase estender e sobe contraindo o bíceps.'],
  ['Curl no cabo', 'biceps', ['forearms'], 'Cabos', 'weight_reps', 'Tensão constante: sobe o pegador com cotovelos fixos e desce devagar.'],
  // Tríceps
  ['Extensão de tríceps na polia (corda)', 'triceps', [], 'Cabos', 'weight_reps', 'Cotovelos junto ao corpo, estende os braços abrindo a corda no fim.'],
  ['Skull crusher', 'triceps', [], 'Barra', 'weight_reps', 'Deitado, desce a barra em direção à testa dobrando só os cotovelos e estende.'],
  ['Extensão de tríceps acima da cabeça', 'triceps', [], 'Halteres', 'weight_reps', 'Haltere atrás da cabeça, estende os braços para cima mantendo os cotovelos apontados à frente.'],
  ['Supino fechado', 'triceps', ['chest', 'shoulders'], 'Barra', 'weight_reps', 'Pega à largura dos ombros, cotovelos junto ao corpo ao descer e empurrar.'],
  ['Fundos no banco', 'triceps', ['shoulders', 'chest'], 'Banco', 'bodyweight_reps', 'Mãos no banco atrás de ti, desce dobrando os cotovelos e empurra.'],
  // Pernas
  ['Agachamento livre com barra', 'quads', ['glutes', 'hamstrings', 'lower_back'], 'Barra', 'weight_reps', 'Barra nos trapézios, pés à largura dos ombros. Desce com o peito aberto até ao paralelo e sobe empurrando o chão.'],
  ['Agachamento frontal', 'quads', ['glutes', 'abs'], 'Barra', 'weight_reps', 'Barra à frente nos ombros, cotovelos altos. Desce mantendo o tronco vertical.'],
  ['Leg press 45°', 'quads', ['glutes', 'hamstrings'], 'Máquina', 'weight_reps', 'Costas coladas, desce até ~90° sem levantar a anca e empurra sem bloquear os joelhos.'],
  ['Extensão de pernas', 'quads', [], 'Máquina', 'weight_reps', 'Estende os joelhos até ao topo e desce controlado.'],
  ['Passada com halteres', 'quads', ['glutes', 'hamstrings'], 'Halteres', 'weight_reps', 'Passo à frente e desce o joelho de trás em direção ao chão; empurra para voltar.'],
  ['Agachamento búlgaro', 'quads', ['glutes'], 'Halteres', 'weight_reps', 'Pé de trás apoiado num banco. Desce na vertical e sobe empurrando com a perna da frente.'],
  ['Hack squat', 'quads', ['glutes'], 'Máquina', 'weight_reps', 'Costas no encosto, desce até ao paralelo e empurra.'],
  ['Stiff (levantamento terra romeno)', 'hamstrings', ['glutes', 'lower_back'], 'Barra', 'weight_reps', 'Joelhos ligeiramente fletidos, empurra a anca para trás com costas neutras até sentir alongar os isquiotibiais.'],
  ['Curl de pernas deitado', 'hamstrings', ['calves'], 'Máquina', 'weight_reps', 'Flete os joelhos levando os calcanhares aos glúteos e desce devagar.'],
  ['Curl de pernas sentado', 'hamstrings', [], 'Máquina', 'weight_reps', 'Flete os joelhos contra a resistência e volta controlado.'],
  ['Hip thrust', 'glutes', ['hamstrings'], 'Barra', 'weight_reps', 'Costas apoiadas no banco, empurra a anca para cima contraindo os glúteos no topo.'],
  ['Elevação de gémeos em pé', 'calves', [], 'Máquina', 'weight_reps', 'Sobe o mais alto possível nas pontas dos pés e desce alongando bem.'],
  ['Elevação de gémeos sentado', 'calves', [], 'Máquina', 'weight_reps', 'Joelhos a 90°, sobe nas pontas dos pés com pausa no topo.'],
  ['Adução na máquina', 'adductors', [], 'Máquina', 'weight_reps', 'Junta as pernas contra a resistência sem balançar.'],
  ['Abdução na máquina', 'glutes', [], 'Máquina', 'weight_reps', 'Abre as pernas contra a resistência com o tronco estável.'],
  // Abdominais
  ['Abdominais no chão (crunch)', 'abs', [], 'Peso corporal', 'bodyweight_reps', 'Sobe apenas os ombros contraindo o abdómen, sem puxar o pescoço.'],
  ['Elevação de pernas suspenso', 'abs', ['forearms'], 'Barra fixa', 'bodyweight_reps', 'Pendurado, sobe as pernas controladas sem balançar.'],
  ['Prancha', 'abs', ['shoulders', 'glutes'], 'Peso corporal', 'duration', 'Apoio nos antebraços, corpo em linha reta, abdómen e glúteos contraídos.'],
  ['Roda abdominal', 'abs', ['lats', 'shoulders'], 'Roda abdominal', 'bodyweight_reps', 'De joelhos, rola para a frente até onde conseguires manter a coluna neutra e volta.'],
  ['Crunch no cabo', 'abs', [], 'Cabos', 'weight_reps', 'De joelhos, flete o tronco levando os cotovelos aos joelhos.'],
  ['Rotação russa', 'obliques', ['abs'], 'Halteres', 'weight_reps', 'Sentado inclinado, roda o tronco de um lado para o outro com controlo.'],
  // Antebraços e cardio
  ['Curl de pulso', 'forearms', [], 'Barra', 'weight_reps', 'Antebraços apoiados, flete e estende os pulsos com amplitude completa.'],
  ['Passadeira', 'cardio', ['quads', 'calves'], 'Passadeira', 'duration', 'Ritmo constante ou intervalos, conforme o objetivo do treino.'],
  ['Bicicleta estática', 'cardio', ['quads'], 'Bicicleta', 'duration', 'Resistência moderada, cadência estável.'],
  ['Remo (ergómetro)', 'cardio', ['lats', 'upper_back', 'quads'], 'Remo', 'duration', 'Empurra com as pernas, depois inclina o tronco e puxa com os braços.'],
  ['Corda de saltar', 'cardio', ['calves'], 'Corda', 'duration', 'Saltos curtos e rápidos, cotovelos junto ao corpo.'],
  // Corpo inteiro
  ['Kettlebell swing', 'full_body', ['glutes', 'hamstrings', 'lower_back'], 'Kettlebell', 'weight_reps', 'Empurra a anca para trás e projeta o kettlebell com a força das ancas, não dos braços.'],
  ['Clean and press', 'full_body', ['shoulders', 'quads', 'glutes'], 'Barra', 'weight_reps', 'Leva a barra do chão aos ombros num movimento explosivo e empurra acima da cabeça.'],
];
